import Head from 'next/head'
import Image from 'next/image'
import { ContentWrapper } from '../components/ContentWrapper'
import { Header } from '../components/Header'
import { MenuTabs } from '../components/MenuTabs'
import { Wallpaper } from '../components/Wallpaper'
import { ProductCard } from '../components/ProductCard'
import styles from '../styles/Home.module.css'
import products from '../stubbs/products.json'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Marimor kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Wallpaper />
      <MenuTabs />
      <main className={styles.content}>
        <ContentWrapper>
          <div className={styles.productsWrap}>
            {products.content.map(product => (
              <ProductCard key={product.id} />
            ))}
          </div>
        </ContentWrapper>
      </main>
      <footer className={styles.footer}>
        <ContentWrapper>
          <div className={styles.footerContent}>
            <div className={styles.socials}>
              <div className={styles.instagram} />
              <div className={styles.whatsapp} />
            </div>
            <div className={styles.rights}>
              MariMor © 2022 All Rights Reserved.
            </div>
          </div>
        </ContentWrapper>
      </footer>
    </div>
  )
}
